# Production values for next-application-for-cypress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: next-application-for-cypress

image:
  repository: amidostacksprodeuwcore.azurecr.io/core/next-application-for-cypress

ingress:
  hosts:
    - host: next-application-for-cypress.prod.amidostacks.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - prod.amidostacks.com

podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: 'false'
